const PrestasiList = [
  {
    id: 1,
    category: "education",
    year: "2023",
    title: "Pencak Silat Kelas D PI SMA/SMK Sederajat yang diselenggarakan oleh UDINUS",
    desc: "Trophy/Uang Pembinaan",
    rate: "Juara II",
  },
  {
    id: 2,
    category: "education",
    year: "2023",
    title: "Lomba Web Design Techcomfest Tingkat Nasional",
    desc: "Trophy/Uang Pembinaan",
    rate: "Juara I",
  },
  {
      id: 3,
      category: "education",
    year: "2023",
    title: "Lomba Perisai Diri CUP 'Perebutan Piala Rektor UNIKA' Kelas E Putri Remaja",
    desc: "Medali/Piagam",
    rate: "Juara I",
  },
  {
      id: 4,
    category: "education",
    year: "2023",
    title: "Lomba Perisai Diri CUP 'Perebutan Piala Rektor UNIKA' Kelas C Putri Remaja",
    desc: "Medali/Piagam",
    rate: "Juara II",
  },
  {
    id: 5,
    category: "education",
    year: "2023",
    title: "Lomba Formasi Pengibaran Bendera, Lomba AKSI PASKIBRA se-Karesidenan Semarang",
    rate: "Juara Terbaik",
  },
  {
    id: 6,
    category: "education",
    year: "2023",
    title: "Medali Emas dan Perak Lomba POPDA (Pekan Olahraga Pelajar Daerah) Cabang Renang Tingkat Kota Semarang",
    rate: "Medali Emas dan Perak",
  },
  {
    id: 7,
    category: "education",
    year: "2023",
    title: "Kids Talents Competition yang diselenggarakan oleh Kementerian Perhubungan Direktorat Jenderal Perhubungan Darat BPTD Wilayah X Provinsi Jateng dan DIY",
    rate: "Juara II",
    },
  {
    id: 8,
    category: "education",
    year: "2023",
    title: "LKS SMK Bidang Lomba Graphics Design Technology Tingkat Kota Semarang",
    rate: "Juara II",
    },
  {
    id: 9,
    category: "experience",
    year: "2022",
    title: "Lomba Keterampilan Siswa (LKS) SMK Bidang Lomba Cloud Computing Tingkat Kota Semarang",
    rate: "Juara I",
    },
  {
    id: 10,
    category: "experience",
    year: "2022",
    title: "LKS SMK Bidang Lomba Cyber Security Tingkat Kota Semarang",
    rate: "Juara II",
    },
  {
    id: 11,
    category: "experience",
    year: "2022",
    title: "LKS SMK Bidang Lomba Cloud Computing Tingkat Jawa Tengah",
    rate: "Juara III",
    },
  {
    id: 11,
    category: "experience",
    year: "2022",
    title: "LKS SMK Bidang Lomba Health Social Care Tingkat Jawa Tengah",
    rate: "Juara II",
    },
  {
    id: 12,
    category: "experience",
    year: "2022",
    title: "Semarang Pencak Silat Open Championship",
    rate: "Juara III",
    },
  {
    id: 13,
    category: "experience",
    year: "2022",
    title: "Semarang Pencak Silat Open Championship Kategori Tanding Kelas I Putra Remaja",
    rate: "Juara II",
    },
  {
    id: 14,
    category: "experience",
    year: "2022",
    title: "Lomba Pertolongan Pertama (P3K) PMI Kota Semarang",
    rate: "Juara Harapan I",
  },
  {
    id: 15,
    category: "experience",
    year: "2022",
    title: "Kejuaraan Bulu Tangkis Multi Kota/Kabupaten Se-Karesidenan Semarang",
    rate: "Juara III",
  },
  {
    id: 16,
    category: "experience",
    year: "2022",
    title: "Kejuaraan Pencak Silat Putri Tingkat Provinsi Kelas Seni Tunggal Putri",
    rate: "Juara Harapan III",
  },
  {
    id: 17,
    category: "experience",
    year: "2022",
    title: "Lomba Festival Pelajar Nusantara di RRI Kategori Student Explore",
    rate: "Juara II",
  },
  {
    id: 18,
    category: "experience",
    year: "2022",
    title: "Inventation 2022 Web Design",
    rate: "Juara Favorit",
  },
  {
    id: 19,
    category: "experience",
    year: "2022",
    title: "Moks Open National Taekwondo Championship",
    rate: "Juara I dan III",
  },
  {
    id: 20,
    category: "experience",
    year: "2022",
    title: "Porprov (Pekan Olahraga Provinsi) Cabang Olahraga Drum Band",
    rate: "Juara I",
  },
  {
    id: 21,
    category: "experience",
    year: "2022",
    title: "Vocal Group Competition",
    rate: "Juara II dan Harapan III",
  },
  {
    id: 21,
    category: "experience",
    year: "2022",
    title: "Lomba Seni Tari Tradisional Tingkat Pelajar SMA/SMK Kota Semarang",
    rate: "Juara III",
  },

]

export default PrestasiList
